# Generated by Django 5.1.2 on 2025-02-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_note_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="created_at",
            new_name="timestamp",
        ),
    ]
