# Generated by Django 5.1.2 on 2025-08-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("link", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="achievements/")),
                ("issuer", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="award",
            name="image",
            field=models.ImageField(blank=True, upload_to="achievements/"),
        ),
    ]
