# Generated by Django 5.1.2 on 2025-08-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_certificate_alter_award_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Higher numbers = cooler projects (displayed first)",
            ),
        ),
    ]
