# Generated by Django 5.1.2 on 2025-08-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_project_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("SWE", "Software Engineering"),
                    ("RESEARCH", "Research"),
                    ("OTHER", "Other"),
                ],
                default="SWE",
                max_length=10,
            ),
        ),
    ]
