# Generated by Django 5.1.2 on 2025-08-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="demo_type",
            field=models.CharField(
                choices=[("VIDEO", "Video"), ("IFRAME", "Iframe"), ("NONE", "No Demo")],
                default="NONE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="demo_url",
            field=models.URLField(
                blank=True, help_text="YouTube embed URL or Google Drive embed URL"
            ),
        ),
    ]
