# Generated by Django 5.1.2 on 2025-08-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_project_demo_type_project_demo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="paper_url",
            field=models.URLField(blank=True),
        ),
    ]
